name: generate docs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  doxygen:
    name: Generate Doxygen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
      - name: Generate Doxygen
        run: |
          doxygen \
          -c laboratories/cicd-documentation/Doxyfile \
          -o laboratories/cicd-documentation/html
      - name: Upload Doxygen
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            laboratories/cicd-documentation/html
