name: generate docs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  doxygen:
    name: Generate Doxygen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Doxygen
        uses: docker://doxygen/doxygen:latest
        with:
          args: |
            -c laboratories/cicd-documentation/Doxyfile
            -o laboratories/cicd-documentation/html
      - name: Upload Doxygen
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            laboratories/cicd-documentation/html
